<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
          
            <h4 class="page-title"><strong><?php echo empty($form_caption) ? "" : $form_caption; ?></strong></h4>
        </div>
    </div>
</div>     
<!-- end page title --> 

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <?php
                    $validation_errors = validation_errors();
                    if (!empty($validation_errors))
                    {
                        ?>
                        <div class="col-xs-12 alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert"
                                    aria-hidden="true">
                                &times;
                            </button>
                            <?php echo $validation_errors; ?>
                        </div>
                        <?php
                    }

                    $attributes = array('id' => 'employee-form', 'class' => 'form-horizontal');
                    echo form_open_multipart('', $attributes);
                ?>
                <div class="form-group">


                    <div class="form-row align-items-center">
                        <label class="col-sm-1 col-form-label">Search</label>
                        <div class="col-sm-11">
                            <input type="text"   id="search" class="form-control" value="" placeholder="Search value...">
                        </div>
                    </div>




                </div>
                <table class="table table-bordered" id="myTable">
                    <tr>
                        <th>S.no</th>
                        <th id="visitors_name" style="cursor: pointer">Visitors Name</th>
                        <th id="pin" style="cursor: pointer">Visitors Pin</th>
                        <th id="visitors_mobile_no" style="cursor: pointer">Visitors Mobile No</th>
                        <th id="property_number" style="cursor: pointer">Property No</th>
                        <th id="visitor_host" style="cursor: pointer">Generated BY</th>
                        <th id="visitor_host" style="cursor: pointer">Generated AT</th>
                        <th>Remove</th>
                    </tr>

                    <tbody id="mytbody">
                        <?php
                            if (!empty($visitor_data))
                            {
                                $i = 1;
                                foreach ($visitor_data as $employee)
                                {
                                    ?>
                                    <tr id="<?php echo $employee['pin']; ?>">
                                        <td style="text-align: center" class="sno"><?php echo $i; ?></td>
                                        <td style="text-align: center"><?php echo $employee['visitors_name']; ?></td>
                                        <td style="text-align: center"><?php echo $employee['pin']; ?></td>
                                        <td style="text-align: center"><?php echo $employee["visitors_mobile_no"]; ?></td>
                                        <td style="text-align: center"><?php echo $employee["property_number"]; ?></td>
                                        <td style="text-align: center"><?php echo $employee["visitor_host"]; ?></td>
                                        <td style="text-align: center"><?php echo $employee["dt"] . '  ' . $employee["t"]; ?></td>
                                        <td style="text-align: center"><button  data-pin="<?php echo $employee['pin']; ?>" data-empid="<?php echo $employee['employee_id']; ?>" data-created="<?php echo $employee['created_by']; ?>" type="button" class="btn btn-danger btn-sm btn-rounded remove_visitor" >Remove</button></td>
                                    </tr>
                                    <?php
                                    $i++;
                                }
                            }
                        ?>
                    </tbody>
                </table>

                <?php echo form_close(); ?>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div><!-- end col -->
</div>
<!-- end row -->
<script>



    $('.remove_visitor').click(function () {
        var employee_pin = $(this).data('pin');
        var employee_created = $(this).data('created');
        var employee_id = $(this).data('empid');


        $.blockUI();
        $.ajax({
            type: "POST",
            url: base_url + 'admin/expired_visitor_report/remove_visitor/',
            data: {employee_pin: employee_pin, employee_created: employee_created, employee_id: employee_id},
        }).done(function () {
            $("#" + employee_pin).remove();
        }).always(function () {
            $.unblockUI();
        });

    });

</script>





<script>

    jQuery.fn.sortElements = (function () {

        var sort = [].sort;

        return function (comparator, getSortable) {

            getSortable = getSortable || function () {
                return this;
            };
            var placements = this.map(function () {

                var sortElement = getSortable.call(this),
                        parentNode = sortElement.parentNode,
                        // Since the element itself will change position, we have
                        // to have some way of storing it's original position in
                        // the DOM. The easiest way is to have a 'flag' node:
                        nextSibling = parentNode.insertBefore(
                                document.createTextNode(''),
                                sortElement.nextSibling
                                );

                return function () {

                    if (parentNode === this) {
                        throw new Error(
                                "You can't sort elements if any one is a descendant of another."
                                );
                    }

                    // Insert before flag:
                    parentNode.insertBefore(this, nextSibling);
                    // Remove flag:
                    parentNode.removeChild(nextSibling);

                };

            });

            return sort.call(this, comparator).each(function (i) {
                placements[i].call(getSortable.call(this));
            });
        };
        //  

    })();
    $(document).ready(function () {
        var table = $('table');
        $('#visitors_name,#pin,#visitors_mobile_no,#visitor_host')
                .wrapInner('<span title="sort this column"/>')
                .each(function () {
                    var th = $(this),
                            thIndex = th.index(),
                            inverse = false;
                    th.click(function () {
                        blockUI();
                        table.find('td').filter(function () {
                            return $(this).index() === thIndex;
                        }).sortElements(function (a, b) {

                            return $.text([a]) > $.text([b]) ? inverse ? -1 : 1 : inverse ? 1 : -1;
                        }, function () {
                            // parentNode is the element we want to move
                            return this.parentNode;
                        });
                        setIndex();
                        inverse = !inverse;
                        $.unblockUI();
                    });
                });
    });
    $("#search").on("keyup", function () {
        var value = $(this).val().toLowerCase();
        $("#mytbody > tr").filter(function () {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
            setsearchIndex();
        });

    });
    function setIndex() {
        $("td.sno").each(function (index) {
            $(this).text(++index);
        });
    }

    function setsearchIndex() {
        $("#myTable tr:visible>td.sno").each(function (index) {
            $(this).text(++index);
        });
    }

</script>
